// ~~ Generated by projen. To modify, edit .projenrc.ts and run "npx projen".
import { aws_appsync } from 'aws-cdk-lib';

/**
 * AppsyncTypescriptFunctionProps
 */
export interface AppsyncTypescriptFunctionProps {
  /**
   * the data source linked to this AppSync Function.
   * @stability stable
   */
  readonly dataSource: aws_appsync.BaseDataSource;
  /**
   * the GraphQL Api linked to this AppSync Function.
   * @stability stable
   */
  readonly api: aws_appsync.IGraphqlApi;
  /**
   * the response mapping template for the AppSync Function.
   * @default - no response mapping template
   * @stability stable
   */
  readonly responseMappingTemplate?: aws_appsync.MappingTemplate;
  /**
   * the request mapping template for the AppSync Function.
   * @default - no request mapping template
   * @stability stable
   */
  readonly requestMappingTemplate?: aws_appsync.MappingTemplate;
  /**
   * the description for this AppSync Function.
   * @default - no description
   * @stability stable
   */
  readonly description?: string;
  /**
   * the name of the AppSync Function.
   * @stability stable
   */
  readonly name: string;
  /**
   * A map of replacement strings in the bundled code. e.g { ENV: "PROD" }
   */
  readonly replaceStrings?: Record<string, string>;
  /**
   * Flag to enable or disable source maps in bundled code. defaults to false
   */
  readonly sourceMap?: boolean;
  /**
   * Path of typescript file that will be transpiled and bundled
   */
  readonly path: string;
}
